// Code generated by config-gen-go-struct from config.yaml. DO NOT EDIT.

package config

import (
	"sync/atomic"

	"gopkg.in/yaml.v3"
)

type DataDatabaseBizCfg struct {
	DatabaseConf DatabaseConfCfg `yaml:"_database_conf"` // DatabaseConfCfg
}

type DatabaseReadCfg struct {
	Dsn  atomic.Value `yaml:"dsn"`  // string
	Name atomic.Value `yaml:"name"` // string
}

type DatabaseWriteCfg struct {
	Dsn  atomic.Value `yaml:"dsn"`  // string
	Name atomic.Value `yaml:"name"` // string
}

type DatabaseConfCfg struct {
	DatabaseRead    DatabaseReadCfg  `yaml:"_database_read"`    // DatabaseReadCfg
	DatabaseWrite   DatabaseWriteCfg `yaml:"_database_write"`   // DatabaseWriteCfg
	ConnMaxLifetime atomic.Value     `yaml:"conn_max_lifetime"` // string
	MaxIdleConns    atomic.Int64     `yaml:"max_idle_conns"`    // int64
	MaxOpenConns    atomic.Int64     `yaml:"max_open_conns"`    // int64
	MaxSlowtime     atomic.Value     `yaml:"max_slowtime"`      // string
	TablePrefix     atomic.Value     `yaml:"table_prefix"`      // string
}

type DataDatabaseDefaultCfg struct {
	DatabaseConf DatabaseConfCfg `yaml:"_database_conf"` // DatabaseConfCfg
}

type RedisConfDefaultCfg struct {
	Addr     atomic.Value `yaml:"addr"`     // string
	Db       atomic.Int64 `yaml:"db"`       // int64
	Name     atomic.Value `yaml:"name"`     // string
	Password atomic.Value `yaml:"password"` // string
}

type RedisConfCfg struct {
	Default     RedisConfDefaultCfg `yaml:"default"`      // RedisConfDefaultCfg
	MaxSlowtime atomic.Value        `yaml:"max_slowtime"` // string
}

type DataRedisLockCfg struct {
	RedisConf RedisConfCfg `yaml:"_redis_conf"` // RedisConfCfg
}

type DataCfg struct {
	DatabaseBiz     DataDatabaseBizCfg     `yaml:"database_biz"`     // DataDatabaseBizCfg
	DatabaseDefault DataDatabaseDefaultCfg `yaml:"database_default"` // DataDatabaseDefaultCfg
	RedisLock       DataRedisLockCfg       `yaml:"redis_lock"`       // DataRedisLockCfg
}

type GeneralLoggerCfg struct {
	Compress         atomic.Bool  `yaml:"compress"`          // bool
	Filename         atomic.Value `yaml:"filename"`          // string
	FilenameConsumer atomic.Value `yaml:"filename_consumer"` // string
	FilenameScript   atomic.Value `yaml:"filename_script"`   // string
	FilenameTest     atomic.Value `yaml:"filename_test"`     // string
	Level            atomic.Value `yaml:"level"`             // string
	MaxAge           atomic.Int64 `yaml:"max_age"`           // int64
	MaxBackup        atomic.Int64 `yaml:"max_backup"`        // int64
	MaxSize          atomic.Int64 `yaml:"max_size"`          // int64
}

type GeneralCfg struct {
	Env    atomic.Value     `yaml:"env"`    // string
	Logger GeneralLoggerCfg `yaml:"logger"` // GeneralLoggerCfg
	Name   atomic.Value     `yaml:"name"`   // string
}

type ServerHttpCfg struct {
	Addr    atomic.Value `yaml:"addr"`    // string
	Timeout atomic.Value `yaml:"timeout"` // string
}

type ServerCfg struct {
	Http ServerHttpCfg `yaml:"http"` // ServerHttpCfg
}

type ThirdSampleCfg struct {
	Domain atomic.Value `yaml:"domain"` // string
}

type ThirdCfg struct {
	Sample ThirdSampleCfg `yaml:"sample"` // ThirdSampleCfg
}

type Config struct {
	Data    DataCfg    `yaml:"data"`    // DataCfg
	General GeneralCfg `yaml:"general"` // GeneralCfg
	Server  ServerCfg  `yaml:"server"`  // ServerCfg
	Third   ThirdCfg   `yaml:"third"`   // ThirdCfg
}

// Load parses config data and populates Config.
// If c is nil, a new Config is created.
// If c is non-nil, data is merged into c (existing keys are overwritten).
func Load(data []byte, c *Config) error {
	var raw map[string]any
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return err
	}
	if c == nil {
		c = &Config{}
	}
	loadConfig(raw, c)
	return nil
}

func loadDataDatabaseBizCfg(raw map[string]any, c *DataDatabaseBizCfg) {
	for k, v := range raw {
		switch k {
		case "_database_conf":
			if m, ok := v.(map[string]any); ok {
				loadDatabaseConfCfg(m, &c.DatabaseConf)
			}
		}
	}
}

func loadDatabaseReadCfg(raw map[string]any, c *DatabaseReadCfg) {
	for k, v := range raw {
		switch k {
		case "dsn":
			if v != nil {
				c.Dsn.Store(v)
			} else {
				c.Dsn.Store("")
			}
		case "name":
			if v != nil {
				c.Name.Store(v)
			} else {
				c.Name.Store("")
			}
		}
	}
}

func loadDatabaseWriteCfg(raw map[string]any, c *DatabaseWriteCfg) {
	for k, v := range raw {
		switch k {
		case "dsn":
			if v != nil {
				c.Dsn.Store(v)
			} else {
				c.Dsn.Store("")
			}
		case "name":
			if v != nil {
				c.Name.Store(v)
			} else {
				c.Name.Store("")
			}
		}
	}
}

func loadDatabaseConfCfg(raw map[string]any, c *DatabaseConfCfg) {
	for k, v := range raw {
		switch k {
		case "_database_read":
			if m, ok := v.(map[string]any); ok {
				loadDatabaseReadCfg(m, &c.DatabaseRead)
			}
		case "_database_write":
			if m, ok := v.(map[string]any); ok {
				loadDatabaseWriteCfg(m, &c.DatabaseWrite)
			}
		case "conn_max_lifetime":
			if v != nil {
				c.ConnMaxLifetime.Store(v)
			} else {
				c.ConnMaxLifetime.Store("")
			}
		case "max_idle_conns":
			switch n := v.(type) {
			case int:
				c.MaxIdleConns.Store(int64(n))
			case int64:
				c.MaxIdleConns.Store(n)
			}
		case "max_open_conns":
			switch n := v.(type) {
			case int:
				c.MaxOpenConns.Store(int64(n))
			case int64:
				c.MaxOpenConns.Store(n)
			}
		case "max_slowtime":
			if v != nil {
				c.MaxSlowtime.Store(v)
			} else {
				c.MaxSlowtime.Store("")
			}
		case "table_prefix":
			if v != nil {
				c.TablePrefix.Store(v)
			} else {
				c.TablePrefix.Store("")
			}
		}
	}
}

func loadDataDatabaseDefaultCfg(raw map[string]any, c *DataDatabaseDefaultCfg) {
	for k, v := range raw {
		switch k {
		case "_database_conf":
			if m, ok := v.(map[string]any); ok {
				loadDatabaseConfCfg(m, &c.DatabaseConf)
			}
		}
	}
}

func loadRedisConfDefaultCfg(raw map[string]any, c *RedisConfDefaultCfg) {
	for k, v := range raw {
		switch k {
		case "addr":
			if v != nil {
				c.Addr.Store(v)
			} else {
				c.Addr.Store("")
			}
		case "db":
			switch n := v.(type) {
			case int:
				c.Db.Store(int64(n))
			case int64:
				c.Db.Store(n)
			}
		case "name":
			if v != nil {
				c.Name.Store(v)
			} else {
				c.Name.Store("")
			}
		case "password":
			if v != nil {
				c.Password.Store(v)
			} else {
				c.Password.Store("")
			}
		}
	}
}

func loadRedisConfCfg(raw map[string]any, c *RedisConfCfg) {
	for k, v := range raw {
		switch k {
		case "default":
			if m, ok := v.(map[string]any); ok {
				loadRedisConfDefaultCfg(m, &c.Default)
			}
		case "max_slowtime":
			if v != nil {
				c.MaxSlowtime.Store(v)
			} else {
				c.MaxSlowtime.Store("")
			}
		}
	}
}

func loadDataRedisLockCfg(raw map[string]any, c *DataRedisLockCfg) {
	for k, v := range raw {
		switch k {
		case "_redis_conf":
			if m, ok := v.(map[string]any); ok {
				loadRedisConfCfg(m, &c.RedisConf)
			}
		}
	}
}

func loadDataCfg(raw map[string]any, c *DataCfg) {
	for k, v := range raw {
		switch k {
		case "database_biz":
			if m, ok := v.(map[string]any); ok {
				loadDataDatabaseBizCfg(m, &c.DatabaseBiz)
			}
		case "database_default":
			if m, ok := v.(map[string]any); ok {
				loadDataDatabaseDefaultCfg(m, &c.DatabaseDefault)
			}
		case "redis_lock":
			if m, ok := v.(map[string]any); ok {
				loadDataRedisLockCfg(m, &c.RedisLock)
			}
		}
	}
}

func loadGeneralLoggerCfg(raw map[string]any, c *GeneralLoggerCfg) {
	for k, v := range raw {
		switch k {
		case "compress":
			if b, ok := v.(bool); ok {
				c.Compress.Store(b)
			}
		case "filename":
			if v != nil {
				c.Filename.Store(v)
			} else {
				c.Filename.Store("")
			}
		case "filename_consumer":
			if v != nil {
				c.FilenameConsumer.Store(v)
			} else {
				c.FilenameConsumer.Store("")
			}
		case "filename_script":
			if v != nil {
				c.FilenameScript.Store(v)
			} else {
				c.FilenameScript.Store("")
			}
		case "filename_test":
			if v != nil {
				c.FilenameTest.Store(v)
			} else {
				c.FilenameTest.Store("")
			}
		case "level":
			if v != nil {
				c.Level.Store(v)
			} else {
				c.Level.Store("")
			}
		case "max_age":
			switch n := v.(type) {
			case int:
				c.MaxAge.Store(int64(n))
			case int64:
				c.MaxAge.Store(n)
			}
		case "max_backup":
			switch n := v.(type) {
			case int:
				c.MaxBackup.Store(int64(n))
			case int64:
				c.MaxBackup.Store(n)
			}
		case "max_size":
			switch n := v.(type) {
			case int:
				c.MaxSize.Store(int64(n))
			case int64:
				c.MaxSize.Store(n)
			}
		}
	}
}

func loadGeneralCfg(raw map[string]any, c *GeneralCfg) {
	for k, v := range raw {
		switch k {
		case "env":
			if v != nil {
				c.Env.Store(v)
			} else {
				c.Env.Store("")
			}
		case "logger":
			if m, ok := v.(map[string]any); ok {
				loadGeneralLoggerCfg(m, &c.Logger)
			}
		case "name":
			if v != nil {
				c.Name.Store(v)
			} else {
				c.Name.Store("")
			}
		}
	}
}

func loadServerHttpCfg(raw map[string]any, c *ServerHttpCfg) {
	for k, v := range raw {
		switch k {
		case "addr":
			if v != nil {
				c.Addr.Store(v)
			} else {
				c.Addr.Store("")
			}
		case "timeout":
			if v != nil {
				c.Timeout.Store(v)
			} else {
				c.Timeout.Store("")
			}
		}
	}
}

func loadServerCfg(raw map[string]any, c *ServerCfg) {
	for k, v := range raw {
		switch k {
		case "http":
			if m, ok := v.(map[string]any); ok {
				loadServerHttpCfg(m, &c.Http)
			}
		}
	}
}

func loadThirdSampleCfg(raw map[string]any, c *ThirdSampleCfg) {
	for k, v := range raw {
		switch k {
		case "domain":
			if v != nil {
				c.Domain.Store(v)
			} else {
				c.Domain.Store("")
			}
		}
	}
}

func loadThirdCfg(raw map[string]any, c *ThirdCfg) {
	for k, v := range raw {
		switch k {
		case "sample":
			if m, ok := v.(map[string]any); ok {
				loadThirdSampleCfg(m, &c.Sample)
			}
		}
	}
}

func loadConfig(raw map[string]any, c *Config) {
	for k, v := range raw {
		switch k {
		case "data":
			if m, ok := v.(map[string]any); ok {
				loadDataCfg(m, &c.Data)
			}
		case "general":
			if m, ok := v.(map[string]any); ok {
				loadGeneralCfg(m, &c.General)
			}
		case "server":
			if m, ok := v.(map[string]any); ok {
				loadServerCfg(m, &c.Server)
			}
		case "third":
			if m, ok := v.(map[string]any); ok {
				loadThirdCfg(m, &c.Third)
			}
		}
	}
}
