// Code generated by config-gen-go-struct from a.json. DO NOT EDIT.

package config

import (
	"sync/atomic"
	"encoding/json"
)

type ConfigA struct {
	General atomic.Value `json:"general"` // string
	Id atomic.Value `json:"id"` // float64
}

// Load parses config data and populates ConfigA.
// If c is nil, a new ConfigA is created.
// If c is non-nil, data is merged into c (existing keys are overwritten).
func LoadA(data []byte, c *ConfigA) error {
	var raw map[string]any
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if c == nil {
		c = &ConfigA{}
	}
	loadConfigA(raw, c)
	return nil
}

func loadConfigA(raw map[string]any, c *ConfigA) {
	for k, v := range raw {
		switch k {
		case "general":
			if v != nil {
				c.General.Store(v)
			} else {
				c.General.Store("")
			}
		case "id":
			if v != nil {
				c.Id.Store(v)
			} else {
				c.Id.Store("")
			}
		}
	}
}

