// Code generated by config-gen-go-struct. DO NOT EDIT.

package config

import "gopkg.in/yaml.v3"

// Config holds all application configuration sections.
type Config struct {
	ConfigA
	ConfigData
	ConfigGeneral
	ConfigServer
	ConfigThird
}

// Cfg is the package-level default config instance.
var Cfg = &Config{}

// Load parses YAML data and populates the corresponding section by name.
func Load(c *Config, name string, data []byte) error {
	if c == nil {
		c = &Config{}
	}
	var raw map[string]any
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch name {
	case "a.json":
		loadConfigA(raw, &c.ConfigA)
	case "data.yaml":
		loadConfigData(raw, &c.ConfigData)
	case "general.yaml":
		loadConfigGeneral(raw, &c.ConfigGeneral)
	case "server.yaml":
		loadConfigServer(raw, &c.ConfigServer)
	case "third.yaml":
		loadConfigThird(raw, &c.ConfigThird)
	}
	return nil
}
