// Code generated by config-gen-go-struct from data.yaml. DO NOT EDIT.

package config

import (
	"sync/atomic"

	"gopkg.in/yaml.v3"
)

type DataDatabaseBizCfg struct {
	DatabaseConf DataDatabaseConfCfg `yaml:"_database_conf"` // DataDatabaseConfCfg
}

type DataDatabaseReadCfg struct {
	Dsn atomic.Value `yaml:"dsn"` // string
	Name atomic.Value `yaml:"name"` // string
}

type DataDatabaseWriteCfg struct {
	Dsn atomic.Value `yaml:"dsn"` // string
	Name atomic.Value `yaml:"name"` // string
}

type DataDatabaseConfCfg struct {
	DatabaseRead DataDatabaseReadCfg `yaml:"_database_read"` // DataDatabaseReadCfg
	DatabaseWrite DataDatabaseWriteCfg `yaml:"_database_write"` // DataDatabaseWriteCfg
	ConnMaxLifetime atomic.Value `yaml:"conn_max_lifetime"` // string
	MaxIdleConns atomic.Int64 `yaml:"max_idle_conns"` // int64
	MaxOpenConns atomic.Int64 `yaml:"max_open_conns"` // int64
	MaxSlowtime atomic.Value `yaml:"max_slowtime"` // string
	TablePrefix atomic.Value `yaml:"table_prefix"` // string
}

type DataDatabaseDefaultCfg struct {
	DatabaseConf DataDatabaseConfCfg `yaml:"_database_conf"` // DataDatabaseConfCfg
}

type DataRedisConfDefaultCfg struct {
	Addr atomic.Value `yaml:"addr"` // string
	Db atomic.Int64 `yaml:"db"` // int64
	Name atomic.Value `yaml:"name"` // string
	Password atomic.Value `yaml:"password"` // string
}

type DataRedisConfCfg struct {
	Default DataRedisConfDefaultCfg `yaml:"default"` // DataRedisConfDefaultCfg
	MaxSlowtime atomic.Value `yaml:"max_slowtime"` // string
}

type DataRedisLockCfg struct {
	RedisConf DataRedisConfCfg `yaml:"_redis_conf"` // DataRedisConfCfg
}

type DataCfg struct {
	DatabaseBiz DataDatabaseBizCfg `yaml:"database_biz"` // DataDatabaseBizCfg
	DatabaseDefault DataDatabaseDefaultCfg `yaml:"database_default"` // DataDatabaseDefaultCfg
	RedisLock DataRedisLockCfg `yaml:"redis_lock"` // DataRedisLockCfg
}

type ConfigData struct {
	Data DataCfg `yaml:"data"` // DataCfg
}

// Load parses config data and populates ConfigData.
// If c is nil, a new ConfigData is created.
// If c is non-nil, data is merged into c (existing keys are overwritten).
func LoadData(data []byte, c *ConfigData) error {
	var raw map[string]any
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return err
	}
	if c == nil {
		c = &ConfigData{}
	}
	loadConfigData(raw, c)
	return nil
}

func loadDataDatabaseBizCfg(raw map[string]any, c *DataDatabaseBizCfg) {
	for k, v := range raw {
		switch k {
		case "_database_conf":
			if m, ok := v.(map[string]any); ok {
				loadDataDatabaseConfCfg(m, &c.DatabaseConf)
			}
		}
	}
}

func loadDataDatabaseReadCfg(raw map[string]any, c *DataDatabaseReadCfg) {
	for k, v := range raw {
		switch k {
		case "dsn":
			if v != nil {
				c.Dsn.Store(v)
			} else {
				c.Dsn.Store("")
			}
		case "name":
			if v != nil {
				c.Name.Store(v)
			} else {
				c.Name.Store("")
			}
		}
	}
}

func loadDataDatabaseWriteCfg(raw map[string]any, c *DataDatabaseWriteCfg) {
	for k, v := range raw {
		switch k {
		case "dsn":
			if v != nil {
				c.Dsn.Store(v)
			} else {
				c.Dsn.Store("")
			}
		case "name":
			if v != nil {
				c.Name.Store(v)
			} else {
				c.Name.Store("")
			}
		}
	}
}

func loadDataDatabaseConfCfg(raw map[string]any, c *DataDatabaseConfCfg) {
	for k, v := range raw {
		switch k {
		case "_database_read":
			if m, ok := v.(map[string]any); ok {
				loadDataDatabaseReadCfg(m, &c.DatabaseRead)
			}
		case "_database_write":
			if m, ok := v.(map[string]any); ok {
				loadDataDatabaseWriteCfg(m, &c.DatabaseWrite)
			}
		case "conn_max_lifetime":
			if v != nil {
				c.ConnMaxLifetime.Store(v)
			} else {
				c.ConnMaxLifetime.Store("")
			}
		case "max_idle_conns":
			switch n := v.(type) {
			case int:
				c.MaxIdleConns.Store(int64(n))
			case int64:
				c.MaxIdleConns.Store(n)
			}
		case "max_open_conns":
			switch n := v.(type) {
			case int:
				c.MaxOpenConns.Store(int64(n))
			case int64:
				c.MaxOpenConns.Store(n)
			}
		case "max_slowtime":
			if v != nil {
				c.MaxSlowtime.Store(v)
			} else {
				c.MaxSlowtime.Store("")
			}
		case "table_prefix":
			if v != nil {
				c.TablePrefix.Store(v)
			} else {
				c.TablePrefix.Store("")
			}
		}
	}
}

func loadDataDatabaseDefaultCfg(raw map[string]any, c *DataDatabaseDefaultCfg) {
	for k, v := range raw {
		switch k {
		case "_database_conf":
			if m, ok := v.(map[string]any); ok {
				loadDataDatabaseConfCfg(m, &c.DatabaseConf)
			}
		}
	}
}

func loadDataRedisConfDefaultCfg(raw map[string]any, c *DataRedisConfDefaultCfg) {
	for k, v := range raw {
		switch k {
		case "addr":
			if v != nil {
				c.Addr.Store(v)
			} else {
				c.Addr.Store("")
			}
		case "db":
			switch n := v.(type) {
			case int:
				c.Db.Store(int64(n))
			case int64:
				c.Db.Store(n)
			}
		case "name":
			if v != nil {
				c.Name.Store(v)
			} else {
				c.Name.Store("")
			}
		case "password":
			if v != nil {
				c.Password.Store(v)
			} else {
				c.Password.Store("")
			}
		}
	}
}

func loadDataRedisConfCfg(raw map[string]any, c *DataRedisConfCfg) {
	for k, v := range raw {
		switch k {
		case "default":
			if m, ok := v.(map[string]any); ok {
				loadDataRedisConfDefaultCfg(m, &c.Default)
			}
		case "max_slowtime":
			if v != nil {
				c.MaxSlowtime.Store(v)
			} else {
				c.MaxSlowtime.Store("")
			}
		}
	}
}

func loadDataRedisLockCfg(raw map[string]any, c *DataRedisLockCfg) {
	for k, v := range raw {
		switch k {
		case "_redis_conf":
			if m, ok := v.(map[string]any); ok {
				loadDataRedisConfCfg(m, &c.RedisConf)
			}
		}
	}
}

func loadDataCfg(raw map[string]any, c *DataCfg) {
	for k, v := range raw {
		switch k {
		case "database_biz":
			if m, ok := v.(map[string]any); ok {
				loadDataDatabaseBizCfg(m, &c.DatabaseBiz)
			}
		case "database_default":
			if m, ok := v.(map[string]any); ok {
				loadDataDatabaseDefaultCfg(m, &c.DatabaseDefault)
			}
		case "redis_lock":
			if m, ok := v.(map[string]any); ok {
				loadDataRedisLockCfg(m, &c.RedisLock)
			}
		}
	}
}

func loadConfigData(raw map[string]any, c *ConfigData) {
	for k, v := range raw {
		switch k {
		case "data":
			if m, ok := v.(map[string]any); ok {
				loadDataCfg(m, &c.Data)
			}
		}
	}
}

