// Code generated by config-gen-go-struct from general.yaml. DO NOT EDIT.

package config

import (
	"sync/atomic"

	"gopkg.in/yaml.v3"
)

type GeneralLoggerCfg struct {
	Compress atomic.Bool `yaml:"compress"` // bool
	Filename atomic.Value `yaml:"filename"` // string
	Level atomic.Value `yaml:"level"` // string
	MaxAge atomic.Int64 `yaml:"max_age"` // int64
	MaxBackup atomic.Int64 `yaml:"max_backup"` // int64
	MaxSize atomic.Int64 `yaml:"max_size"` // int64
}

type GeneralCfg struct {
	Env atomic.Value `yaml:"env"` // string
	Ip atomic.Value `yaml:"ip"` // string
	Logger GeneralLoggerCfg `yaml:"logger"` // GeneralLoggerCfg
	Name atomic.Value `yaml:"name"` // string
	Version atomic.Value `yaml:"version"` // string
}

type ConfigGeneral struct {
	General GeneralCfg `yaml:"general"` // GeneralCfg
}

// Load parses config data and populates ConfigGeneral.
// If c is nil, a new ConfigGeneral is created.
// If c is non-nil, data is merged into c (existing keys are overwritten).
func LoadGeneral(data []byte, c *ConfigGeneral) error {
	var raw map[string]any
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return err
	}
	if c == nil {
		c = &ConfigGeneral{}
	}
	loadConfigGeneral(raw, c)
	return nil
}

func loadGeneralLoggerCfg(raw map[string]any, c *GeneralLoggerCfg) {
	for k, v := range raw {
		switch k {
		case "compress":
			if b, ok := v.(bool); ok {
				c.Compress.Store(b)
			}
		case "filename":
			if v != nil {
				c.Filename.Store(v)
			} else {
				c.Filename.Store("")
			}
		case "level":
			if v != nil {
				c.Level.Store(v)
			} else {
				c.Level.Store("")
			}
		case "max_age":
			switch n := v.(type) {
			case int:
				c.MaxAge.Store(int64(n))
			case int64:
				c.MaxAge.Store(n)
			}
		case "max_backup":
			switch n := v.(type) {
			case int:
				c.MaxBackup.Store(int64(n))
			case int64:
				c.MaxBackup.Store(n)
			}
		case "max_size":
			switch n := v.(type) {
			case int:
				c.MaxSize.Store(int64(n))
			case int64:
				c.MaxSize.Store(n)
			}
		}
	}
}

func loadGeneralCfg(raw map[string]any, c *GeneralCfg) {
	for k, v := range raw {
		switch k {
		case "env":
			if v != nil {
				c.Env.Store(v)
			} else {
				c.Env.Store("")
			}
		case "ip":
			if v != nil {
				c.Ip.Store(v)
			} else {
				c.Ip.Store("")
			}
		case "logger":
			if m, ok := v.(map[string]any); ok {
				loadGeneralLoggerCfg(m, &c.Logger)
			}
		case "name":
			if v != nil {
				c.Name.Store(v)
			} else {
				c.Name.Store("")
			}
		case "version":
			if v != nil {
				c.Version.Store(v)
			} else {
				c.Version.Store("")
			}
		}
	}
}

func loadConfigGeneral(raw map[string]any, c *ConfigGeneral) {
	for k, v := range raw {
		switch k {
		case "general":
			if m, ok := v.(map[string]any); ok {
				loadGeneralCfg(m, &c.General)
			}
		}
	}
}

