// Code generated by config-gen-go-struct from server.yaml. DO NOT EDIT.

package config

import (
	"sync/atomic"

	"gopkg.in/yaml.v3"
)

type ServerHttpCfg struct {
	Addr atomic.Value `yaml:"addr"` // string
	Timeout atomic.Value `yaml:"timeout"` // string
}

type ServerCfg struct {
	Http ServerHttpCfg `yaml:"http"` // ServerHttpCfg
}

type ConfigServer struct {
	Server ServerCfg `yaml:"server"` // ServerCfg
}

// Load parses config data and populates ConfigServer.
// If c is nil, a new ConfigServer is created.
// If c is non-nil, data is merged into c (existing keys are overwritten).
func LoadServer(data []byte, c *ConfigServer) error {
	var raw map[string]any
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return err
	}
	if c == nil {
		c = &ConfigServer{}
	}
	loadConfigServer(raw, c)
	return nil
}

func loadServerHttpCfg(raw map[string]any, c *ServerHttpCfg) {
	for k, v := range raw {
		switch k {
		case "addr":
			if v != nil {
				c.Addr.Store(v)
			} else {
				c.Addr.Store("")
			}
		case "timeout":
			if v != nil {
				c.Timeout.Store(v)
			} else {
				c.Timeout.Store("")
			}
		}
	}
}

func loadServerCfg(raw map[string]any, c *ServerCfg) {
	for k, v := range raw {
		switch k {
		case "http":
			if m, ok := v.(map[string]any); ok {
				loadServerHttpCfg(m, &c.Http)
			}
		}
	}
}

func loadConfigServer(raw map[string]any, c *ConfigServer) {
	for k, v := range raw {
		switch k {
		case "server":
			if m, ok := v.(map[string]any); ok {
				loadServerCfg(m, &c.Server)
			}
		}
	}
}

