// Code generated by config-gen-go-struct from third.yaml. DO NOT EDIT.

package config

import (
	"sync/atomic"

	"gopkg.in/yaml.v3"
)

type ThirdSampleCfg struct {
	Domain atomic.Value `yaml:"domain"` // string
}

type ThirdCfg struct {
	Sample ThirdSampleCfg `yaml:"sample"` // ThirdSampleCfg
}

type ConfigThird struct {
	Third ThirdCfg `yaml:"third"` // ThirdCfg
}

// Load parses config data and populates ConfigThird.
// If c is nil, a new ConfigThird is created.
// If c is non-nil, data is merged into c (existing keys are overwritten).
func LoadThird(data []byte, c *ConfigThird) error {
	var raw map[string]any
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return err
	}
	if c == nil {
		c = &ConfigThird{}
	}
	loadConfigThird(raw, c)
	return nil
}

func loadThirdSampleCfg(raw map[string]any, c *ThirdSampleCfg) {
	for k, v := range raw {
		switch k {
		case "domain":
			if v != nil {
				c.Domain.Store(v)
			} else {
				c.Domain.Store("")
			}
		}
	}
}

func loadThirdCfg(raw map[string]any, c *ThirdCfg) {
	for k, v := range raw {
		switch k {
		case "sample":
			if m, ok := v.(map[string]any); ok {
				loadThirdSampleCfg(m, &c.Sample)
			}
		}
	}
}

func loadConfigThird(raw map[string]any, c *ConfigThird) {
	for k, v := range raw {
		switch k {
		case "third":
			if m, ok := v.(map[string]any); ok {
				loadThirdCfg(m, &c.Third)
			}
		}
	}
}

