package main

import (
	"bytes"
	"fmt"
	"strings"
)

func generateContent(pkg string, info dirInfo) []byte {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by wire-gen-go-provider. DO NOT EDIT.\n")
	buf.WriteString("// Matches '^func New' or '^type WireFieldsOf' per package.\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg)
	buf.WriteString("import (\n\t\"github.com/google/wire\"\n)\n\n")
	buf.WriteString("var ProviderSet = wire.NewSet(\n")

	for _, p := range info.providers {
		fmt.Fprintf(&buf, "\t%s,\n", p)
	}
	for _, fo := range info.fieldsOf {
		args := strings.Join(fo.fields, `", "`)
		fmt.Fprintf(&buf, "\twire.FieldsOf(new(*%s), \"%s\"),\n", fo.structName, args)
	}

	buf.WriteString(")\n")
	return buf.Bytes()
}
