package main

import (
	"fmt"
	"strings"
)

func generate(pkg, typeName, loadName string, fields []fieldInfo, srcFile, format string) string {
	var b strings.Builder

	b.WriteString("// Code generated by config-gen-go-struct from " + srcFile + ". DO NOT EDIT.\n\n")
	b.WriteString("package " + pkg + "\n\n")

	genImports(&b, format)

	genStructs := map[string]bool{}
	genStruct(&b, typeName, fields, 0, genStructs)

	b.WriteString("// Load parses config data and populates " + typeName + ".\n")
	b.WriteString("// If c is nil, a new " + typeName + " is created.\n")
	b.WriteString("// If c is non-nil, data is merged into c (existing keys are overwritten).\n")
	b.WriteString("func " + loadName + "(data []byte, c *" + typeName + ") error {\n")
	b.WriteString("\tvar raw map[string]any\n")
	b.WriteString("\tif err := " + decoderCall(format) + "(data, &raw); err != nil {\n")
	b.WriteString("\t\treturn err\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif c == nil {\n")
	b.WriteString("\t\tc = &" + typeName + "{}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tload" + typeName + "(raw, c)\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")

	genLoadFunc(&b, typeName, fields, map[string]bool{})
	genDecoder(&b, format)

	return b.String()
}

func decoderCall(format string) string {
	switch format {
	case "json":
		return "json.Unmarshal"
	case "ini":
		return "decodeIni"
	default:
		return "yaml.Unmarshal"
	}
}

func genDecoder(b *strings.Builder, format string) {
	if format != "ini" {
		return
	}
	b.WriteString("func decodeIni(data []byte, raw *map[string]any) error {\n")
	b.WriteString("\tsections := parseIni(string(data))\n")
	b.WriteString("\tmerged := make(map[string]any)\n")
	b.WriteString("\tfor section, kv := range sections {\n")
	b.WriteString("\t\tif section == \"\" {\n")
	b.WriteString("\t\t\tfor k, v := range kv {\n")
	b.WriteString("\t\t\t\tmerged[k] = v\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t} else {\n")
	b.WriteString("\t\t\tsub := make(map[string]any)\n")
	b.WriteString("\t\t\tfor k, v := range kv {\n")
	b.WriteString("\t\t\t\tsub[k] = v\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tmerged[section] = sub\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\t*raw = merged\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func parseIni(raw string) map[string]map[string]string {\n")
	b.WriteString("\tsections := map[string]map[string]string{}\n")
	b.WriteString("\tcurrent := \"\"\n")
	b.WriteString("\tfor _, line := range strings.Split(raw, \"\\n\") {\n")
	b.WriteString("\t\tline = strings.TrimSpace(line)\n")
	b.WriteString("\t\tif line == \"\" || strings.HasPrefix(line, \";\") || strings.HasPrefix(line, \"#\") {\n")
	b.WriteString("\t\t\tcontinue\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tif strings.HasPrefix(line, \"[\") {\n")
	b.WriteString("\t\t\tif end := strings.Index(line, \"]\"); end > 0 {\n")
	b.WriteString("\t\t\t\tcurrent = line[1:end]\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tcontinue\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tkey, val, ok := strings.Cut(line, \"=\")\n")
	b.WriteString("\t\tif !ok {\n")
	b.WriteString("\t\t\tcontinue\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tkey = strings.TrimSpace(key)\n")
	b.WriteString("\t\tval = strings.TrimSpace(val)\n")
	b.WriteString("\t\tif sections[current] == nil {\n")
	b.WriteString("\t\t\tsections[current] = map[string]string{}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tsections[current][key] = val\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn sections\n")
	b.WriteString("}\n\n")
}

func genImports(b *strings.Builder, format string) {
	b.WriteString("import (\n\t\"sync/atomic\"\n")
	switch format {
	case "json":
		b.WriteString("\t\"encoding/json\"\n")
	case "ini":
		b.WriteString("\t\"fmt\"\n")
		b.WriteString("\t\"reflect\"\n")
		b.WriteString("\t\"strings\"\n")
	default:
		b.WriteString("\n\t\"gopkg.in/yaml.v3\"\n")
	}
	b.WriteString(")\n\n")
}

func genImportsSplit(b *strings.Builder, format string) {
	switch format {
	case "json":
		b.WriteString("import \"encoding/json\"\n\n")
	case "ini":
		b.WriteString("import (\n\t\"fmt\"\n\t\"reflect\"\n\t\"strings\"\n)\n\n")
	default:
		b.WriteString("import \"gopkg.in/yaml.v3\"\n\n")
	}
}

func genStruct(b *strings.Builder, name string, fields []fieldInfo, depth int, generated map[string]bool) {
	if generated[name] {
		return
	}

	indent := strings.Repeat("\t", depth)

	for _, f := range fields {
		if f.IsStruct {
			genStruct(b, f.StructType, f.Children, depth, generated)
		}
	}

	if len(fields) == 0 {
		return
	}

	generated[name] = true

	fmt.Fprintf(b, "%stype %s struct {\n", indent, name)
	for _, f := range fields {
		tag := fmt.Sprintf("`yaml:%q`", f.Key)
		fmt.Fprintf(b, "%s\t%s %s %s // %s\n", indent, f.Name, f.AtomicType, tag, f.GoType)
	}
	fmt.Fprintf(b, "%s}\n\n", indent)
}

func genLoadFunc(b *strings.Builder, name string, fields []fieldInfo, generated map[string]bool) {
	if generated[name] {
		return
	}

	funcName := "load" + name

	for _, f := range fields {
		if f.IsStruct {
			genLoadFunc(b, f.StructType, f.Children, generated)
		}
	}

	if len(fields) == 0 {
		return
	}

	generated[name] = true

	fmt.Fprintf(b, "func %s(raw map[string]any, c *%s) {\n", funcName, name)
	fmt.Fprintf(b, "\tfor k, v := range raw {\n")
	fmt.Fprintf(b, "\t\tswitch k {\n")
	for _, f := range fields {
		fmt.Fprintf(b, "\t\tcase %q:\n", f.Key)
		genStore(b, f)
	}
	fmt.Fprintf(b, "\t\t}\n")
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "}\n\n")
}

// generateSplit returns a map of filename -> content, splitting top-level sections
// into separate files. baseName is the file prefix (e.g. "config.dev").
func generateSplit(pkg, typeName string, fields []fieldInfo, srcFile, format, baseName string) map[string]string {
	files := map[string]string{}

	var sections []fieldInfo
	for _, f := range fields {
		if f.IsStruct && len(f.Children) > 0 {
			sections = append(sections, f)
		}
	}

	// Section files — deep generate each section's subtree
	for _, sf := range sections {
		buf := &strings.Builder{}
		fmt.Fprintf(buf, "// Code generated by config-gen-go-struct from %s. DO NOT EDIT.\n\n", srcFile)
		buf.WriteString("package " + pkg + "\n\n")
		buf.WriteString("import \"sync/atomic\"\n\n")

		genStruct(buf, sf.StructType, sf.Children, 0, map[string]bool{})
		genLoadFunc(buf, sf.StructType, sf.Children, map[string]bool{})

		sectionName := strings.ToLower(sf.Name)
		files[baseName+"_"+sectionName+".cfg.go"] = buf.String()
	}

	// Main file
	mainBuf := &strings.Builder{}
	fmt.Fprintf(mainBuf, "// Code generated by config-gen-go-struct from %s. DO NOT EDIT.\n\n", srcFile)
	mainBuf.WriteString("package " + pkg + "\n\n")
	genImportsSplit(mainBuf, format)

	if len(sections) > 0 {
		genStructShallow(mainBuf, typeName, fields, 0, map[string]bool{})
	} else {
		genStruct(mainBuf, typeName, fields, 0, map[string]bool{})
	}

	mainBuf.WriteString("// Load parses config data and populates " + typeName + ".\n")
	mainBuf.WriteString("// If c is nil, a new " + typeName + " is created.\n")
	mainBuf.WriteString("// If c is non-nil, data is merged into c (existing keys are overwritten).\n")
	fmt.Fprintf(mainBuf, "func Load(data []byte, c *%s) error {\n", typeName)
	mainBuf.WriteString("\tvar raw map[string]any\n")
	mainBuf.WriteString("\tif err := " + decoderCall(format) + "(data, &raw); err != nil {\n")
	mainBuf.WriteString("\t\treturn err\n")
	mainBuf.WriteString("\t}\n")
	mainBuf.WriteString("\tif c == nil {\n")
	mainBuf.WriteString("\t\tc = &" + typeName + "{}\n")
	mainBuf.WriteString("\t}\n")
	mainBuf.WriteString("\tload" + typeName + "(raw, c)\n")
	mainBuf.WriteString("\treturn nil\n")
	mainBuf.WriteString("}\n\n")

	genLoadFuncShallow(mainBuf, typeName, fields, map[string]bool{})
	genDecoder(mainBuf, format)

	files[baseName+".cfg.go"] = mainBuf.String()
	return files
}

func genStructShallow(b *strings.Builder, name string, fields []fieldInfo, depth int, generated map[string]bool) {
	if generated[name] || len(fields) == 0 {
		return
	}
	generated[name] = true

	indent := strings.Repeat("\t", depth)
	fmt.Fprintf(b, "%stype %s struct {\n", indent, name)
	for _, f := range fields {
		tag := fmt.Sprintf("`yaml:%q`", f.Key)
		fmt.Fprintf(b, "%s\t%s %s %s // %s\n", indent, f.Name, f.AtomicType, tag, f.GoType)
	}
	fmt.Fprintf(b, "%s}\n\n", indent)
}

func genLoadFuncShallow(b *strings.Builder, name string, fields []fieldInfo, generated map[string]bool) {
	if generated[name] || len(fields) == 0 {
		return
	}
	generated[name] = true

	funcName := "load" + name
	fmt.Fprintf(b, "func %s(raw map[string]any, c *%s) {\n", funcName, name)
	fmt.Fprintf(b, "\tfor k, v := range raw {\n")
	fmt.Fprintf(b, "\t\tswitch k {\n")
	for _, f := range fields {
		fmt.Fprintf(b, "\t\tcase %q:\n", f.Key)
		genStore(b, f)
	}
	fmt.Fprintf(b, "\t\t}\n")
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "}\n\n")
}

func genStore(b *strings.Builder, f fieldInfo) {
	switch {
	case f.IsStruct:
		fmt.Fprintf(b, "\t\t\tif m, ok := v.(map[string]any); ok {\n")
		fmt.Fprintf(b, "\t\t\t\tload%s(m, &c.%s)\n", f.StructType, f.Name)
		fmt.Fprintf(b, "\t\t\t}\n")
	case f.AtomicType == "atomic.Int64":
		fmt.Fprintf(b, "\t\t\tswitch n := v.(type) {\n")
		fmt.Fprintf(b, "\t\t\tcase int:\n")
		fmt.Fprintf(b, "\t\t\t\tc.%s.Store(int64(n))\n", f.Name)
		fmt.Fprintf(b, "\t\t\tcase int64:\n")
		fmt.Fprintf(b, "\t\t\t\tc.%s.Store(n)\n", f.Name)
		fmt.Fprintf(b, "\t\t\t}\n")
	case f.AtomicType == "atomic.Bool":
		fmt.Fprintf(b, "\t\t\tif b, ok := v.(bool); ok {\n")
		fmt.Fprintf(b, "\t\t\t\tc.%s.Store(b)\n", f.Name)
		fmt.Fprintf(b, "\t\t\t}\n")
	default:
		fmt.Fprintf(b, "\t\t\tif v != nil {\n")
		fmt.Fprintf(b, "\t\t\t\tc.%s.Store(v)\n", f.Name)
		fmt.Fprintf(b, "\t\t\t} else {\n")
		fmt.Fprintf(b, "\t\t\t\tc.%s.Store(\"\")\n", f.Name)
		fmt.Fprintf(b, "\t\t\t}\n")
	}
}

// unifiedEntry describes a single config section for the unified Config struct.
type unifiedEntry struct {
	structName string // e.g. "ConfigData"
	loadName   string // e.g. "LoadData"
	yamlFile   string // e.g. "data.yaml"
}

// generateUnified produces the unified config.go that aggregates all sections.
func generateUnified(pkg, typeName string, entries []unifiedEntry) string {
	var b strings.Builder

	b.WriteString("// Code generated by config-gen-go-struct. DO NOT EDIT.\n\n")
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("import \"gopkg.in/yaml.v3\"\n\n")

	b.WriteString("// Config holds all application configuration sections.\n")
	b.WriteString("type " + typeName + " struct {\n")
	for _, e := range entries {
		b.WriteString("\t" + e.structName + "\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("// Cfg is the package-level default config instance.\n")
	b.WriteString("var Cfg = &" + typeName + "{}\n\n")

	b.WriteString("// Load parses YAML data and populates the corresponding section by name.\n")
	b.WriteString("func Load(c *" + typeName + ", name string, data []byte) error {\n")
	b.WriteString("\tif c == nil {\n")
	b.WriteString("\t\tc = &" + typeName + "{}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tvar raw map[string]any\n")
	b.WriteString("\tif err := yaml.Unmarshal(data, &raw); err != nil {\n")
	b.WriteString("\t\treturn err\n")
	b.WriteString("\t}\n")
	b.WriteString("\tswitch name {\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "\tcase %q:\n", e.yamlFile)
		fmt.Fprintf(&b, "\t\tload%s(raw, &c.%s)\n", e.structName, e.structName)
	}
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n")

	return b.String()
}
